name: Generate Allure Reports

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-allure-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jdk maven

      - name: Set up Allure
        run: |
          curl -o allure-2.13.8.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
          sudo tar -zxvf allure-2.13.8.tgz -C /opt/
          sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure
          allure --version

      - name: Build and test
        run: |
          mvn clean test
          allure generate Allure --clean
          ls -lah

      - name: Push Allure reports to gh-pages branch
        run: |
          git checkout gh_pages
          git config user.email "ksht1994@gmail.com"
          git config user.name "Kshitij3003"
          cp -r allure-report/* .
          rm -rf allure-report/
          git add .
          git commit -m "Add Allure reports"
          git branch --set-upstream-to=origin/main gh_pages
          git pull
          git push https://Kshitij3003:${{ secrets.GHACTION_SECRET }}@github.com/Kshitij3003/GitHub-Action---GitHub-Pages.git
